#ifndef TOKENS_H
#define TOKENS_H

enum {
  ASSIGN = '=', LTN = '<',GTN = '>', PLUS='+',MINUS='-',
  STAR='*',DIV='/',REM='%',NOT='!',
  LPAREN='(',RPAREN=')',LBRACK='[',RBRACK=']',
  LBRACE='{',RBRACE='}',SEMI=';',COMMA=',',

  AUTO = 256,BREAK,CASE,CHAR,CONST,CONTINUE,DEFAULT,DO,DOUBLE,
  ELSE,ENUM,EXTERN,FLOAT,FOR,GOTO,IF,INT,LONG,REGISTER,
  RETURN,SHORT,SIGNED,SIZEOF,STATIC,STRUCT,SWITCH,TYPEDEF,
  UNION,UNSIGNED,VOID,VOLATILE,WHILE,

  OR,AND,EQL,NEQ,LEQ,GEQ,INC,DEC,
  NAME,NUM,STRLIT,CHARLIT,DONE=0,ERROR=-1
};
# endif /*TOKENS_H*/
